#############################################################################
# Makefile for building: risGen
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  risGen.pro
# Template: app
# Command: /home/denes/Qt/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile risGen.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.5/gcc_64/include -I../../../Qt/5.5/gcc_64/include/QtWidgets -I../../../Qt/5.5/gcc_64/include/QtGui -I../../../Qt/5.5/gcc_64/include/QtCore -I. -I. -I../../../Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/denes/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = risGen1.0.0
DISTDIR = /home/denes/Documents/Labor/risGen/.tmp/risGen1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/denes/Qt/5.5/gcc_64 -Wl,-rpath,/home/denes/Qt/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/denes/Qt/5.5/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		moc_widget.o
DIST          = ../../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		risGen.pro widget.h main.cpp \
		widget.cpp
QMAKE_TARGET  = risGen
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = risGen


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: risGen.pro ../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		risGen.pro \
		/home/denes/Qt/5.5/gcc_64/lib/libQt5Widgets.prl \
		/home/denes/Qt/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/denes/Qt/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile risGen.pro
../../../Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.5/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.5/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/uic.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.5/gcc_64/mkspecs/features/lex.prf:
risGen.pro:
/home/denes/Qt/5.5/gcc_64/lib/libQt5Widgets.prl:
/home/denes/Qt/5.5/gcc_64/lib/libQt5Gui.prl:
/home/denes/Qt/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile risGen.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: ../../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QFile \
		widget.h
	/home/denes/Qt/5.5/gcc_64/bin/moc $(DEFINES) -I/home/denes/Qt/5.5/gcc_64/mkspecs/linux-g++ -I/home/denes/Documents/Labor/risGen -I/home/denes/Qt/5.5/gcc_64/include -I/home/denes/Qt/5.5/gcc_64/include/QtWidgets -I/home/denes/Qt/5.5/gcc_64/include/QtGui -I/home/denes/Qt/5.5/gcc_64/include/QtCore widget.h -o moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/home/denes/Qt/5.5/gcc_64/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.5/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		widget.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../../Qt/5.5/gcc_64/include/QtCore/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QWidget \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QFile \
		ui_widget.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QVariant \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QAction \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qaction.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QButtonGroup \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QCheckBox \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qcheckbox.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QGroupBox \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qgroupbox.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QHBoxLayout \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qboxlayout.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qlayout.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qgridlayout.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QHeaderView \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qheaderview.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qstyleoption.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qvalidator.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qregularexpression.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qslider.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qabstractslider.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qstyle.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qtabbar.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qrubberband.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QPushButton \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qpushbutton.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QRadioButton \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qradiobutton.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QSpacerItem \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QTextEdit \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtextdocument.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtextoption.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtextcursor.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qtextformat.h \
		../../../Qt/5.5/gcc_64/include/QtGui/qpen.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QVBoxLayout \
		../../../Qt/5.5/gcc_64/include/QtWidgets/QFileDialog \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qfiledialog.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.5/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.5/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/5.5/gcc_64/include/QtCore/QTextStream \
		../../../Qt/5.5/gcc_64/include/QtCore/QRegExp \
		../../../Qt/5.5/gcc_64/include/QtCore/QDir
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

